name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_plugin_manager/version.py'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
      - name: Build Source Packages
        run: |
          python setup.py sdist
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel
      - name: Install package
        run: |
          pip install .