name: Run License Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
      - name: Install core repo
        run: |
          pip install .
      - name: Get explicit and transitive dependencies
        run: |
          pip freeze > requirements-all.txt
      - name: Check python
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v0.5.0
        with:
          requirements: 'requirements-all.txt'
          fail: 'Copyleft,Other,Error'
          fails-only: true
          exclude: '^(tqdm).*'
          exclude-license: '^(Mozilla).*$'
      - name: Print report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"